### ISSUE TITLE
Add documentation to install the application

### ISSUE THREAD

**Issue by lyrixx** [usmonster/emoji-master#20]
Hello.

@Diwann from Blablacar showed me this application (I guess), and I like it.
I would like to setup it on our slack.

Could you provide installation instruction ? :yellow_heart: 

Thanks

**Comment by usmonster** [comment]
Hi @lyrixx! Thanks for your interest in the app. It makes me happy to know that others want to use it. :)

There are some issues I would want to close before I can feel comfortable recommending the app to someone else, but you can 👍and subscribe to #14 to see when I will add documentation. I have no ETA on it, but knowing there's external interest is motivating. That said, I will close this issue in favor of the other one.

Thanks again! (And thanks @Diwann for your... evangelism. 😉)
